#!/usr/bin/env python3
"""
filter_roles.py — Fast pre-filter before enrichment and scoring.

Reads today_raw.json (output of fetch.py), removes dismissed roles and
clearly out-of-scope roles, writes today.json (surviving roles) and
pre_filtered.json (removed roles + reason, used by /feed for skipped section).

Personal filter rules come from my_filters.json (gitignored, generated by
/feed-setup). If my_filters.json doesn't exist, only the comp floor filter
(from sources.md) and the learnings.md rejected patterns apply.

Pipeline: fetch.py → filter_roles.py → enrich.py → /feed
"""

import json
import re
from pathlib import Path

FEED_AGENT  = Path(__file__).parent
BASE        = FEED_AGENT.parent
TODAY_RAW   = FEED_AGENT / "today_raw.json"
TODAY       = FEED_AGENT / "today.json"
FILTERED    = FEED_AGENT / "pre_filtered.json"
DISMISSED   = FEED_AGENT / "dismissed.json"
LEARNINGS   = FEED_AGENT / "learnings.md"
SOURCES     = BASE / "context" / "sources.md"
MY_FILTERS  = FEED_AGENT / "my_filters.json"


def load_my_filters():
    """Load personal filter rules from my_filters.json. Returns empty defaults if missing."""
    if not MY_FILTERS.exists():
        return {}
    return json.loads(MY_FILTERS.read_text())


def load_rejected_patterns():
    """
    Parse learnings.md ## Rejected section into (company, [keywords]) pairs.

    Lines look like:
      - [YYYY-MM-DD] Company — Role title — reason | signal:...

    Extracts meaningful keywords (4+ chars, not stopwords) from the role title.
    Matching requires company substring match AND all keywords present in title.
    """
    if not LEARNINGS.exists():
        return []

    STOPWORDS = {
        "senior", "staff", "lead", "principal", "manager", "product",
        "the", "and", "of", "for", "in", "a", "an", "to", "new", "with"
    }

    patterns = []
    in_rejected = False
    for line in LEARNINGS.read_text().splitlines():
        stripped = line.strip()
        if stripped == "## Rejected":
            in_rejected = True
            continue
        if stripped.startswith("## ") and in_rejected:
            break
        if not in_rejected or not stripped.startswith("- ["):
            continue
        m = re.match(r"- \[\d{4}-\d{2}-\d{2}\] (.+?) — (.+?) —", stripped)
        if m:
            company   = m.group(1).strip().lower()
            raw_title = m.group(2).strip().lower()
            keywords = [
                re.sub(r"[^a-z0-9]", "", w)
                for w in raw_title.split()
                if len(w.strip(",.;:")) >= 4 and w.strip(",.;:") not in STOPWORDS
            ]
            keywords = [k for k in keywords if k]
            if company and keywords:
                patterns.append((company, keywords))
    return patterns


def matches_rejected_pattern(role, rejected_patterns):
    company = role.get("company", "").lower()
    title   = role.get("title", "").lower()
    title_clean = re.sub(r"[^a-z0-9 ]", "", title)
    for pat_company, keywords in rejected_patterns:
        if pat_company not in company:
            continue
        if all(kw in title_clean for kw in keywords):
            return f"rejected pattern ({', '.join(keywords[:3])})"
    return None


def matches_any(text, patterns):
    """Return True if text matches any pattern in the list."""
    t = text.lower()
    for p in patterns:
        if re.search(p, t):
            return True
    return False


def is_non_role(title, patterns):
    if not patterns:
        return False
    return matches_any(title, patterns)


def is_international(location, patterns):
    if not patterns:
        return False
    if not location or str(location).strip() in ("", "nan"):
        return False
    return matches_any(location, patterns)


def is_hard_no_domain(title, patterns):
    """Returns reason string if title matches a hard-no pattern, else None."""
    if not patterns:
        return None
    t = title.lower()
    for entry in patterns:
        if re.search(entry["pattern"], t):
            return entry["reason"]
    return None


def is_skip_company(company, skip_list):
    """Returns reason string if company is in the skip list, else None."""
    if not skip_list or not company or str(company).strip() in ("", "nan"):
        return None
    c = company.lower().strip()
    for entry in skip_list:
        name  = entry["name"].lower()
        match = entry.get("match", "substring")
        reason = entry.get("reason", name)
        if match == "exact":
            if c == name or c.startswith(name + " ") or c.endswith(" " + name):
                return f"known skip company ({name})"
        else:
            if name in c:
                return f"known skip company ({name})"
    return None


def load_comp_floor():
    """Parse comp floor from sources.md. Returns floor as int (USD) or None."""
    if not SOURCES.exists():
        return None
    for line in SOURCES.read_text().splitlines():
        m = re.search(r"\$(\d+)K?\s+floor", line)
        if m:
            val = int(m.group(1))
            return val * 1000 if val < 10000 else val
    return None


def is_below_comp_floor(role, floor):
    """
    Returns reason string if the upper end of the comp range is below the floor.
    Only filters when there is a posted range AND the upper end is below floor.
    """
    if not floor:
        return None
    comp = str(role.get("compensation") or "").strip()
    if not comp:
        return None

    amounts = []
    for m in re.finditer(r"\$(\d+(?:\.\d+)?)(K)?", comp):
        val = float(m.group(1))
        if m.group(2):
            val *= 1000
        if "/hr" in comp:
            val *= 2080
        amounts.append(val)

    if not amounts:
        return None

    upper = max(amounts)
    if upper < floor:
        return f"comp upper ${upper/1000:.0f}K below floor ${floor//1000}K"
    return None


def main():
    if not TODAY_RAW.exists():
        print("today_raw.json not found — run fetch.py first")
        raise SystemExit(0)

    roles = json.loads(TODAY_RAW.read_text())

    # ── Dismissed filter (absorbs filter_dismissed.py) ───────────────────────
    if DISMISSED.exists():
        dismissed = set(json.loads(DISMISSED.read_text()).keys())
        before_dismissed = len(roles)
        roles = [r for r in roles if r["id"] not in dismissed]
        removed = before_dismissed - len(roles)
        if removed:
            print(f"Dismissed filter: {removed} removed ({len(roles)} remaining)")

    # ── Load personal filters ─────────────────────────────────────────────────
    my_filters       = load_my_filters()
    non_role_pats    = my_filters.get("non_role_patterns", [])
    hard_no_pats     = my_filters.get("hard_no_title_patterns", [])
    skip_companies   = my_filters.get("skip_companies", [])
    exclude_locs     = my_filters.get("exclude_locations", [])

    if not my_filters:
        print("my_filters.json not found — run /feed-setup to generate personal filters")

    rejected_patterns = load_rejected_patterns()
    comp_floor        = load_comp_floor()
    before            = len(roles)

    surviving = []
    filtered  = []

    for role in roles:
        title    = str(role.get("title", "") or "")
        company  = str(role.get("company", "") or "")
        location = str(role.get("location", "") or "")

        # 1. Wrong role type for this user?
        if is_non_role(title, non_role_pats):
            filtered.append({**role, "_filter_reason": "not target role type"})
            continue

        # 2. Location excluded?
        if is_international(location, exclude_locs):
            filtered.append({**role, "_filter_reason": "excluded location"})
            continue

        # 3. Matches a previously rejected pattern from learnings.md?
        reason = matches_rejected_pattern(role, rejected_patterns)
        if reason:
            filtered.append({**role, "_filter_reason": reason})
            continue

        # 4. Hard-no domain signal in title?
        reason = is_hard_no_domain(title, hard_no_pats)
        if reason:
            filtered.append({**role, "_filter_reason": reason})
            continue

        # 5. Company in skip list?
        reason = is_skip_company(company, skip_companies)
        if reason:
            filtered.append({**role, "_filter_reason": reason})
            continue

        # 6. Comp posted and upper end below floor?
        reason = is_below_comp_floor(role, comp_floor)
        if reason:
            filtered.append({**role, "_filter_reason": reason})
            continue

        surviving.append(role)

    FILTERED.write_text(json.dumps(filtered, indent=2))
    TODAY.write_text(json.dumps(surviving, indent=2))

    by_reason = {}
    for r in filtered:
        key = r["_filter_reason"]
        by_reason[key] = by_reason.get(key, 0) + 1

    print(f"Pre-filter: {before} → {len(surviving)} roles ({before - len(surviving)} removed)")
    for reason, count in sorted(by_reason.items(), key=lambda x: -x[1]):
        print(f"  {count:3d}  {reason}")


if __name__ == "__main__":
    main()
